#version: '3.9'
#
#services:
#  office:
#    container_name: office
#    depends_on:
#      - api
#    build:
#      dockerfile: apps/office/Dockerfile
#      context: .
#    command: >
#      sh -c "npx nx run office:serve:development"
#    restart: unless-stopped
#    ports:
#      - 3000:4200
#    volumes:
#      - .:/app
#      - monorepo-node-modules:/app/node_modules
#
#  api:
#    container_name: api
#    depends_on:
#      - resto_db
#    build:
#      dockerfile: apps/api/Dockerfile
#      context: .
#    command: >
#      sh -c "npx prisma migrate dev
#      && npx nx run api:serve:development"
#    restart: unless-stopped
#    ports:
#      - 4201:4201
#      - 5555:5555
#    volumes:
#      - .:/app
#      - monorepo-node-modules:/app/node_modules
#    networks:
#      - resto
#
#  resto_db:
#    container_name: resto_db
#    image: postgres:latest
#    restart: unless-stopped
#
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - resto_database:/var/lib/postgresql/data
#    networks:
#      - resto
#    ports:
#      - 5432:5432
#
#volumes:
#  monorepo-node-modules:
#  resto_database:
#
#networks:
#  resto:
#    driver: bridge
