version: '3.9'

services:
  resto_db:
    container_name: resto_db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env.local.development
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - resto_database:/var/lib/postgresql/data
    networks:
      - resto
    ports:
      - "5432:5432"

volumes:
  monorepo-node-modules:
  resto_database:

networks:
  resto:
    driver: bridge
