import '@entities/app/init'
import '@entities/authenticated-user/init'
import '@features/login-form/init'
import '@features/user-menu/init'
import '@shared/api/auth/init'
import '@shared/request/init'
